<template>
  <div>
    <el-table
      :data="tableData"
      v-loading="tableLoading"
      style="width: 100%;"
      max-height="500"
      highlight-current-row
      :default-sort = "{prop: 'date', order: 'descending'}">
      <el-table-column
        prop="year"
        label="年"
        fixed="left"
        width="80">
      </el-table-column>
      <el-table-column
        prop="month"
        fixed="left"
        label="月"
        width="50">
      </el-table-column>
      <el-table-column
        prop="area"
        fixed="left"
        label="区域"
        width="100">
      </el-table-column>
      <el-table-column
        prop="province"
        fixed="left"
        label="省办"
        width="100">
      </el-table-column>
      <el-table-column label="年销售目标（净额）" align="center">
        <el-table-column
          prop="targetPercentageQ1"
          label="Q1完成率"
          width="90">
        </el-table-column>
        <el-table-column
          prop="targetBalanceQ1"
          label="Q1差额"
          width="90">
        </el-table-column>
        <el-table-column
          prop="targetPercentageQ2"
          label="Q2完成率"
          width="90">
        </el-table-column>
        <el-table-column
          prop="targetBalanceQ2"
          label="Q2差额"
          width="90">
        </el-table-column>
        <el-table-column
          prop="targetPercentageQ3"
          label="Q3完成率"
          width="90">
        </el-table-column>
        <el-table-column
          prop="targetBalanceQ3"
          label="Q3差额"
          width="90">
        </el-table-column>
        <el-table-column
          prop="targetPercentageQ4"
          label="Q4完成率"
          width="90">
        </el-table-column>
        <el-table-column
          prop="targetBalanceQ4"
          label="Q4差额"
          width="90">
        </el-table-column>
        <el-table-column
          prop="targetPercentage2018"
          label="2018完成率"
          width="100">
        </el-table-column>
        <el-table-column
          prop="targetBalance2018"
          width="100"
          label="2018差额">
        </el-table-column>
        <el-table-column
          prop="quarterlyComplianceRate"
          width="100"
          label="当季达标率">
        </el-table-column>
      </el-table-column>
      <el-table-column label="销售基本盘（订单）" align="center">
        <el-table-column
          prop="baseAmount"
          label="金额"
          width="90">
        </el-table-column>
        <el-table-column
          prop="baseLastYear"
          label="比去年"
          width="90">
        </el-table-column>
        <el-table-column
          prop="baseQuarterTarget"
          label="比次季最高月订单目标"
          width="110">
        </el-table-column>
        <el-table-column
          prop="baseAfterSixMonthTarget"
          label="比后6个月最高月订单目标"
          width="120">
        </el-table-column>
      </el-table-column>
      <el-table-column label="店数" align="center">
        <el-table-column
          prop="quantityExclusiveShop"
          label="营业中专卖店"
          width="90">
        </el-table-column>
        <el-table-column
          prop="quantityNewShop"
          label="新开店"
          width="90">
        </el-table-column>
        <el-table-column
          prop="quantityCloseShop"
          label="关店"
          width="110">
        </el-table-column>
        <el-table-column
          prop="quantityUndeterminedShop"
          label="待定店"
          width="120">
        </el-table-column>
      </el-table-column>
      <el-table-column label="单产" align="center">
        <el-table-column
          prop="yieldAverage"
          label="60%平均单产"
          width="90">
        </el-table-column>
        <el-table-column
          prop="yieldYear2017"
          label="比2017"
          width="90">
        </el-table-column>
        <el-table-column
          prop="yieldYearRate2017"
          label="比2017%"
          width="90">
        </el-table-column>
        <el-table-column
          prop="yieldSellProportion1"
          label="<4万销售占比"
          width="90">
        </el-table-column>
        <el-table-column
          prop="yieldShopQuantityProportion1"
          label="<4万店数占比"
          width="110">
        </el-table-column>
        <el-table-column
          prop="yieldSellProportion2"
          label="4-6万店数占比"
          width="120">
        </el-table-column>
        <el-table-column
          prop="yieldShopQuantityProportion2"
          label="4-6万店数占比"
          width="120">
        </el-table-column>
        <el-table-column
          prop="yieldSellProportion3"
          label=">6万销售占比"
          width="120">
        </el-table-column>
        <el-table-column
          prop="yieldShopQuantityProportion3"
          label=">6万店数占比"
          width="120">
        </el-table-column>
      </el-table-column>
      <el-table-column label="新店成长" align="center">
        <el-table-column
          prop="developmentFirstOrderAmount"
          label="首定金额"
          width="90">
        </el-table-column>
        <el-table-column
          prop="developmentAverageYield"
          label="6月内平均单产"
          width="90">
        </el-table-column>
        <el-table-column
          prop="developmentCloseShopProportion"
          label="一年内关店率"
          width="110">
        </el-table-column>
      </el-table-column>
      <el-table-column label="专卖店信息" align="center">
        <el-table-column
          prop="shopRent"
          label="租金（60%）"
          width="90">
        </el-table-column>
        <el-table-column
          prop="shopAcreage"
          label="面积"
          width="90">
        </el-table-column>
        <el-table-column
          prop="shopClerkWages"
          label="店员工资"
          width="110">
        </el-table-column>
        <el-table-column
          prop="shopQuantityProportionB1"
          label="B1店数占比"
          width="110">
        </el-table-column>
        <el-table-column
          prop="shopQuantityProportionB2"
          label="B2店数占比"
          width="110">
        </el-table-column>
        <el-table-column
          prop="shopQuantityProportionB3"
          label="B3店数占比"
          width="110">
        </el-table-column>
        <el-table-column
          prop="shopQuantityProportionA"
          label="A店数占比"
          width="110">
        </el-table-column>
        <el-table-column
          prop="shopControlRates"
          label="OIO达标率"
          width="110">
        </el-table-column>
        <el-table-column
          prop="shopDb"
          label="DB数"
          width="110">
        </el-table-column>
        <el-table-column
          prop="shopQuantity"
          label="店数/DB"
          width="110">
        </el-table-column>
        <el-table-column
          prop="shopCg"
          label="CG数"
          width="110">
        </el-table-column>
        <el-table-column
          prop="shopSingle"
          label="单挂店"
          width="110">
        </el-table-column>
        <el-table-column
          prop="shopImportantCityQuantity"
          label="重点城市开店数"
          width="110">
        </el-table-column>
      </el-table-column>
      <el-table-column label="QDB" align="center">
        <el-table-column
          prop="qdbQuantity"
          label="QDB数量"
          width="90">
        </el-table-column>
        <el-table-column
          prop="qdbTargetQuantity"
          label="目标数"
          width="90">
        </el-table-column>
        <el-table-column
          prop="qdbIncrease"
          label="净增QDB"
          width="110">
        </el-table-column>
      </el-table-column>
      <el-table-column label="会员" align="center">
        <el-table-column
          prop="memberAmount"
          label="总数"
          width="90">
        </el-table-column>
        <el-table-column
          prop="memberVipQuantity"
          label="VIP数"
          width="90">
        </el-table-column>
        <el-table-column
          prop="memberVipAverage"
          label="月店均VIP"
          width="110">
        </el-table-column>
      </el-table-column>
      <el-table-column label="店员" align="center">
        <el-table-column
          prop="salesclerkAmount"
          label="总数"
          width="90">
        </el-table-column>
        <el-table-column
          prop="salesclerkShopAverage"
          label="店平均"
          width="90">
        </el-table-column>
        <el-table-column
          prop="salesclerkSales"
          label="月销售/店员"
          width="110">
        </el-table-column>
      </el-table-column>
      <el-table-column label="促销" align="center">
        <el-table-column
          prop="firstOrderProportion"
          label="首轮订单占比"
          width="90">
        </el-table-column>
      </el-table-column>
      <el-table-column label="库存" align="center">
        <el-table-column
          prop="inventoryItoDays"
          label="ITO Days"
          width="90">
        </el-table-column>
        <el-table-column
          prop="inventoryNotIto"
          label="不含陈列ITO"
          width="90">
        </el-table-column>
      </el-table-column>
      <el-table-column label="实际零售额" align="center">
        <el-table-column
          prop="retailSalesReality"
          label="实际"
          width="90">
        </el-table-column>
        <el-table-column
          prop="retailSalesComparePlan"
          label="比计划"
          width="90">
        </el-table-column>
        <el-table-column
          prop="retailSalesCompareLastYear"
          label="比去年"
          width="110">
        </el-table-column>
      </el-table-column>
      <el-table-column label="销售净额" align="center">
        <el-table-column
          prop="netAmountReality"
          label="实际"
          width="90">
        </el-table-column>
        <el-table-column
          prop="netAmountComparePlan"
          label="比计划"
          width="90">
        </el-table-column>
        <el-table-column
          prop="netAmountCompareLastYear"
          label="比去年"
          width="110">
        </el-table-column>
      </el-table-column>
      <el-table-column label="营业中专卖店" align="center">
        <el-table-column
          prop="openShopReality"
          label="实际"
          width="90">
        </el-table-column>
        <el-table-column
          prop="openShopComparePlan"
          label="比计划"
          width="90">
        </el-table-column>
        <el-table-column
          prop="openShopCompareLastYear"
          label="比去年"
          width="110">
        </el-table-column>
        <el-table-column
          prop="openShopCompareLastYearRate"
          label="比去年%"
          width="110">
        </el-table-column>
      </el-table-column>
      <el-table-column label="分销商数" align="center">
        <el-table-column
          prop="distributorReality"
          label="实际"
          width="90">
        </el-table-column>
        <el-table-column
          prop="distributorComparePlan"
          label="比计划"
          width="90">
        </el-table-column>
        <el-table-column
          prop="distributorCompareLastYear"
          label="比去年"
          width="110">
        </el-table-column>
      </el-table-column>
      <el-table-column label="VIP会员" align="center">
        <el-table-column
          prop="vipMemberReality"
          label="实际"
          width="90">
        </el-table-column>
        <el-table-column
          prop="vipMemberComparePlan"
          label="比计划"
          width="90">
        </el-table-column>
        <el-table-column
          prop="vipMemberCompareLastYear"
          label="比去年"
          width="110">
        </el-table-column>
      </el-table-column>
      <el-table-column label="综合折扣率" align="center">
        <el-table-column
          prop="comprehensiveReality"
          label="实际"
          width="90">
        </el-table-column>
        <el-table-column
          prop="comprehensiveCompareLastYear"
          label="比去年"
          width="110">
        </el-table-column>
      </el-table-column>
      <el-table-column label="单位费用贡献净额" align="center">
        <el-table-column
          prop="unitReality"
          label="实际"
          width="90">
        </el-table-column>
        <el-table-column
          prop="unitCompareLastYear"
          label="比去年"
          width="110">
        </el-table-column>
      </el-table-column>
      <el-table-column label="毛利率" align="center">
        <el-table-column
          prop="grossMarginComparePlan"
          label="实际"
          width="90">
        </el-table-column>
        <el-table-column
          prop="grossMarginCompareLastYear"
          label="比去年"
          width="110">
        </el-table-column>
      </el-table-column>
    </el-table>
  </div>
</template>

<script>
  export default {
    data() {
      return {
        id:this.$route.params.id,
        loading:false,
        currentPage:1,
        total:0,
        searchForm:{
          pagingQuery:{
            pageIndex:1,
            pageSize:20
          }
        },
        tableData: [
        ],
        tableLoading:false
      }
    },
    watch:{
    },
    methods: {
      gotoUrl(url){
        this.$router.push({ path: url });
      },     
      downLoad(index, row) {
        window.open(row.resultUrl)
      },
      loadData(){
        let thiz = this;
        thiz.tableLoading = true;
        thiz.$tupHttp(thiz,'dashBoard/getTableDetail?tableType=F02','POST',{id:this.id}).then(res=>{
          thiz.tableData = res.body.models;
          thiz.tableLoading = false;
        },res=>{
          thiz.tableLoading = false;
        })
      }
    },
    mounted(){
      this.loadData();
    }
  }
</script>
<style scoped>
.itemsTitle{
  font-size: 20px;
  border-bottom: 1px solid #ccc;
}
.demo-form-inline{
  margin-bottom: 10px;
  padding: 25px  25px 0px;
  border-radius: 4px;
  border: 1px solid #eee;
}
</style>
