<template>
  <div>
    <el-table
      :data="tableData"
      v-loading="tableLoading"
      style="width: 100%;"
      height="500"
      highlight-current-row
      :default-sort = "{prop: 'date', order: 'descending'}">
      <el-table-column
        prop="year"
        label="年"
        fixed="left"
        width="80">
      </el-table-column>
      <el-table-column
        prop="month"
        fixed="left"
        label="月"
        width="50">
      </el-table-column>
      <el-table-column
        prop="area"
        fixed="left"
        label="区域"
        width="100">
      </el-table-column>
      <el-table-column
        prop="province"
        fixed="left"
        label="省办"
        width="100">
      </el-table-column>
      <el-table-column label="2018年订单增长率" align="center">
        <el-table-column
          prop="orderGrowthRateJan"
          label="Jan"
          width="60">
        </el-table-column>
        <el-table-column
          prop="orderGrowthRateFeb"
          label="Feb"
          width="60">
        </el-table-column>
        <el-table-column
          prop="orderGrowthRateMar"
          label="Mar"
          width="60">
        </el-table-column>
        <el-table-column
          prop="orderGrowthRateApr"
          label="Apr"
          width="60">
        </el-table-column>
        <el-table-column
          prop="orderGrowthRateMay"
          label="May"
          width="60">
        </el-table-column>
        <el-table-column
          prop="orderGrowthRateJun"
          label="Jul"
          width="60">
        </el-table-column>
        <el-table-column
          prop="orderGrowthRateJul"
          label="Jul"
          width="60">
        </el-table-column>
        <el-table-column
          prop="orderGrowthRateAug"
          label="Aug"
          width="60">
        </el-table-column>
        <el-table-column
          prop="orderGrowthRateSep"
          label="Sep"
          width="60">
        </el-table-column>
        <el-table-column
          prop="orderGrowthRateOct"
          label="Oct"
          width="60">
        </el-table-column>
        <el-table-column
          prop="orderGrowthRateNov"
          label="Nov"
          width="60">
        </el-table-column>
        <el-table-column
          prop="orderGrowthRateDec"
          label="Dec"
          width="60">
        </el-table-column>
        <el-table-column
          prop="orderGrowthRateQ1"
          label="Q1"
          width="60">
        </el-table-column>
        <el-table-column
          prop="orderGrowthRateQ2"
          label="Q2"
          width="60">
        </el-table-column>
        <el-table-column
          prop="orderGrowthRateQ3"
          label="Q3"
          width="60">
        </el-table-column>
        <el-table-column
          prop="orderGrowthRateQ4"
          label="Q4"
          width="60">
        </el-table-column>
        <el-table-column
          prop="orderGrowthRateTotalYear"
          label="全年"
          width="60">
        </el-table-column>
      </el-table-column>
      <el-table-column label="2018年零售额增长率" align="center">
        <el-table-column
          prop="retailSalesGrowthRateJan"
          label="Jan"
          width="60">
        </el-table-column>
        <el-table-column
          prop="retailSalesGrowthRateFeb"
          label="Feb"
          width="60">
        </el-table-column>
        <el-table-column
          prop="retailSalesGrowthRateMar"
          label="Mar"
          width="60">
        </el-table-column>
        <el-table-column
          prop="retailSalesGrowthRateApr"
          label="Apr"
          width="60">
        </el-table-column>
        <el-table-column
          prop="retailSalesGrowthRateMay"
          label="May"
          width="60">
        </el-table-column>
        <el-table-column
          prop="retailSalesGrowthRateJun"
          label="Jun"
          width="60">
        </el-table-column>
        <el-table-column
          prop="retailSalesGrowthRateJul"
          label="Jul"
          width="60">
        </el-table-column>
        <el-table-column
          prop="retailSalesGrowthRateAug"
          label="Aug"
          width="60">
        </el-table-column>
        <el-table-column
          prop="retailSalesGrowthRateSep"
          label="Sep"
          width="60">
        </el-table-column>
        <el-table-column
          prop="retailSalesGrowthRateOct"
          label="Oct"
          width="60">
        </el-table-column>
        <el-table-column
          prop="retailSalesGrowthRateNov"
          label="Nov"
          width="60">
        </el-table-column>
        <el-table-column
          prop="retailSalesGrowthRateDec"
          label="Dec"
          width="60">
        </el-table-column>
        <el-table-column
          prop="retailSalesGrowthRateQ1"
          label="Q1"
          width="60">
        </el-table-column>
        <el-table-column
          prop="retailSalesGrowthRateQ2"
          label="Q2"
          width="60">
        </el-table-column>
        <el-table-column
          prop="retailSalesGrowthRateQ3"
          label="Q3"
          width="60">
        </el-table-column>
        <el-table-column
          prop="retailSalesGrowthRateQ4"
          label="Q4"
          width="60">
        </el-table-column>
        <el-table-column
          prop="retailSalesGrowthRateTotalYear"
          label="全年"
          width="60">
        </el-table-column>
      </el-table-column>
    </el-table>
  </div>
</template>

<script>
  export default {
    data() {
      return {
        id:this.$route.params.id,
        loading:false,
        currentPage:1,
        total:0,
        searchForm:{
          pagingQuery:{
            pageIndex:1,
            pageSize:20
          }
        },
        tableData: [
        ],
        tableLoading:false
      }
    },
    watch:{
    },
    methods: {
      gotoUrl(url){
        this.$router.push({ path: url });
      },     
      downLoad(index, row) {
        window.open(row.resultUrl)
      },
      loadData(){
        let thiz = this;
        thiz.tableLoading = true;
        thiz.$tupHttp(thiz,'dashBoard/getTableDetail?tableType=F03','POST',{id:this.id}).then(res=>{
          thiz.tableData = res.body.models;
          thiz.tableLoading = false;
        },res=>{
          thiz.tableLoading = false;
        })
      }
    },
    mounted(){
      this.loadData();
    }
  }
</script>
<style scoped>
.itemsTitle{
  font-size: 20px;
  border-bottom: 1px solid #ccc;
}
.demo-form-inline{
  margin-bottom: 10px;
  padding: 25px  25px 0px;
  border-radius: 4px;
  border: 1px solid #eee;
}
</style>
